version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1-stretch-node-browsers
    working_directory: ~/repo
    parallelism: 2
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: install allure CLI
          command: |
            uname -a
            sudo npm install -g allure-commandline --save-dev
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            circleci tests glob tests/**/*.py | circleci tests split |
            python3 -m pytest --alluredir ~/repo/raw_test_result_jsons
      - run:
          name: report
          command: |
            allure generate -c ~/repo/raw_test_result_jsons -o ~/repo/test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports
          when: always